### ISSUE TITLE
Issue about marslife.org - 404 error on some images

### ISSUE THREAD

**Issue by jumpjack** [phaseIV/Blender-Navcam-Importer#14]
I see the marslife site project is not on github, so I post here...

I see a lot of "404 error" in console while loading images for last sol, 2148:

![image](https://user-images.githubusercontent.com/1620953/186957652-5cdfc2c0-b0d9-4da1-84cf-a4c092b8cf5c.png)

This new reference can be used to download images:

https://pds-imaging.jpl.nasa.gov/data/mer/spirit/mer2po_0xxx/browse/sol2148/rdr/

Replacing:
https://mars.nasa.gov/mer/gallery/all/2/n/2148/

I don't see [EFF ](https://mars.nasa.gov/mer/gallery/all/2/n/2148/2N317057419EFFB2GXP1705L0M1.JPG) products, but probably you can use [FFL ](https://pds-imaging.jpl.nasa.gov/data/mer/spirit/mer2no_0xxx/browse/sol2148/rdr/2n317057419fflb2gxp1705l0m1.img.jpg) and [ILF](https://pds-imaging.jpl.nasa.gov/data/mer/spirit/mer2no_0xxx/browse/sol2148/rdr/2n317057419ilfb2gxp1705l0m1.img.jpg).

**Comment by phaseIV** [comment]
sorry, this repo is not about marslife.org and i much rather have a conversation with you by email.
could you please mail me at info@marslife.org.

**Comment by jumpjack** [comment]
I already wrote you.

**Comment by open768** [comment]
@phaseIV is there a repo for marslife.org? I would like to link to specific panoramas from https://www.mars-browser.co.uk/curiosity/ . i have sent you an email a while ago.
