### ISSUE TITLE
Error:Unable to retrieve NAVCAM texture image.

### ISSUE THREAD

**Issue by mmmin1214** [phaseIV/Blender-Navcam-Importer#5]
Hello, 

First I also want to say thank you for such a brilliant addon,
however, it does not work now in both Blender 2.77 and 2.78 and gives the error message_"Unable to retrieve NAVCAM texture image."

I've try more than 30 file names and checked the number of the SOL but it still does not work.
Do you have any advice on this?

**Comment by phaseIV** [comment]
On what OS are you using Blender? Afaik the OSX version does not work anymore.
See the other issue for details.

**Comment by mmmin1214** [comment]
Thanks for such prompt reply, then does it means it will work in Windows?


Best,
Min

**Comment by phaseIV** [comment]
Sorry for the delay. Yes, the addon works fine under Windows.
Please note the ±4 months delay of rover images containing depth data, it's described in the docs.

**Comment by phaseIV** [comment]
Fixed in latest commit by using subprocess/curl for Mac users.
