### ISSUE TITLE
mesh seems squashed on plane

### ISSUE THREAD

**Issue by ericfont** [phaseIV/Blender-Navcam-Importer#6]
Was told the mesh would be ready to render after import, but what I get (on both 3 example images* listed on the instruction) is somehow a mesh squashed on the plane radiating out from the origin, like:

![Screenshot (80)](https://user-images.githubusercontent.com/6502474/63191170-e20fd980-c035-11e9-9f48-2dcf46fd04bf.png)

I apologize I'm not very experienced in blender, so maybe I'm making a noobie mistake.  I'm on Blender 2.80 Windows 10.

*(for Spirit: 2N227484705MRDAS2JP1981L0M1
for Opportunity: 1N142657823MRD3221P1971L0M1
for Curiosity: NLB_499684210EDR_F0501222NCAM00290M_)

**Comment by ericfont** [comment]
Actually, there is some error messages:

![Screenshot (81)](https://user-images.githubusercontent.com/6502474/63193683-1ab2b180-c03c-11e9-91dd-6a8326abf5de.png)

**Comment by ericfont** [comment]
It seems in bpy that that function call in question (https://docs.blender.org/api/current/bpy.types.Image.html#bpy.types.Image.pack) does indeed require arguments to be string data and integer data_len.

**Comment by ericfont** [comment]
So in 2.78 there is https://docs.blender.org/api/blender_python_api_current/bpy.ops.image.html#bpy.ops.image.pack which has argument like your script uses:

bpy.ops.image.pack(as_png=False)

But in 2.80 I see there is https://docs.blender.org/api/current/bpy.ops.image.html#bpy.ops.image.pack which uses no arguments:

bpy.ops.image.pack()

**Comment by ericfont** [comment]
well removing the argument so there is just empty parenthesis on that line just results in a subsequent error... I'm guessing this script isn't *quite* updated for 2.80 yet.

Will try on 2.78 now...

**Comment by ericfont** [comment]
Hmm..trying 2.78c with the v1 of the plugin...still get the same problem.

**Comment by ericfont** [comment]
Earlier versions don't work either...  Tried 2.79a and the final 2.79 nightly on windows running v1, and got the same problem.  Tried 2.80 on Linux running v2, and got the same error message and failure.

I've given up trying to figure out what is wrong.

**Comment by phaseIV** [comment]
Hi ericfont, thanks for reporting and investigating. The addon should work again with the official Blender 2.8 release.

**Comment by ericfont** [comment]
Thanks for the fix.

And yes, now when rendering from the camera it works, thanks.
